version: '3.7'
services:
  mysql:

    image: mysql:8.0
    ports:
      - '3306:3306'


    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app-line
      - MYSQL_PASSWORD=12345

  node-app:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'

  postgres:

    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib
    environment:

      POSTGRES_DB: app
      POSTGRES_USER: app-line
      POSTGRES_PASSWORD: 12345
